name: "MagicPod"
description: "Run batch test"
inputs:
  API_TOKEN:
    description: "API Token"
    required: true
  ORGANIZATION:
    description: "Organization name"
    required: true
  PROJECT:
    description: "Project name"
    required: true
  TEST_SETTINGS_NUMBER:
    description: "Test settings number defined in the project batch run page"
    required: true
    default: "0"
runs:
  using: "node16"
  main: "index.js"
