on: [push]

jobs:
  magic_pod_job:
    runs-on: ubuntu-latest
    name: Run batch test
    steps:
      - name: Run batch test step
        uses: knaot0/magic-pod-action@v1.1
        with:
          API_TOKEN: ${{ secrets.MAGIC_POD_API_TOKEN }}
          ORGANIZATION: "Organization name"
          PROJECT: "Project name"
          TEST_SETTINGS_NUMBER: "1"
